import { createHash } from 'node:crypto';
import { Injectable } from '@nestjs/common';
import type { EntityManager } from 'typeorm';
import { ServiceUnavailableError, UnprocessableError } from '../../core/errors/app-errors.js';
import { IdempotencyKeyEntity } from './idempotency-key.entity.js';

export type IdempotencyRequest = {
  /** Operation the key belongs to, e.g. `areas.create`. Keys of different operations never collide. */
  scope: string;
  key: string;
  /** Id of the resource this request will create, known up front because ids are generated by the app. */
  resourceId: string;
  requestHash: string;
};

export type IdempotencyClaim =
  /** First request with this key: go ahead and create `resourceId`. */
  | { status: 'claimed' }
  /** The key was used before with the same request: return the resource it created. */
  | { status: 'replay'; resourceId: string };

/** SHA-256 (hex) of a validated request; the same key sent with a different request is rejected. */
export function hashRequest(request: unknown): string {
  // Validated request objects are built by the schema, so their key order is stable.
  return createHash('sha256').update(JSON.stringify(request)).digest('hex');
}

/**
 * Implements `Idempotency-Key`: a client that did not receive the response (timeout, dropped
 * connection) can retry the same request safely, and gets the original result instead of a duplicate.
 */
@Injectable()
export class IdempotencyStore {
  /**
   * Claims `key` inside the caller's transaction, before the resource is written.
   *
   * The primary key `(scope, key)` arbitrates between concurrent requests with the same key: the second
   * insert waits for the first transaction, then either inserts (the first rolled back) or does nothing
   * (the first committed) and the request becomes a replay. Because the key row commits together with
   * the resource, a key never points to a resource that does not exist.
   */
  async claim(manager: EntityManager, request: IdempotencyRequest): Promise<IdempotencyClaim> {
    const result = await manager
      .createQueryBuilder()
      .insert()
      .into(IdempotencyKeyEntity)
      .values({
        scope: request.scope,
        key: request.key,
        resourceId: request.resourceId,
        requestHash: request.requestHash,
      })
      .orIgnore()
      .returning('key')
      .execute();
    const insertedRows: unknown = result.raw;
    if (Array.isArray(insertedRows) && insertedRows.length > 0) {
      return { status: 'claimed' };
    }

    const existing = await manager.findOneBy(IdempotencyKeyEntity, {
      scope: request.scope,
      key: request.key,
    });
    if (!existing) {
      // Only possible if the key expired and was deleted between the two statements.
      throw new ServiceUnavailableError('The request could not be completed. Retry it.', 1);
    }
    if (existing.requestHash !== request.requestHash) {
      throw new UnprocessableError(
        'The Idempotency-Key has already been used with a different request.',
      );
    }
    return { status: 'replay', resourceId: existing.resourceId };
  }
}
